#
# Plugin made by Aikidored
# Discord Support Link: https://discord.gg/RYTfade
#

#
# This Plugin Allows Players/Plugins/Console to issue commands or broadcasts to external server instances.
#

#
# Issues? Bugs? Suggestions? Contact me on Discord at https://discord.gg/RYTfade
# 

#
# If you Are Enjoying Remote Commands Please leave a review on Spigot https://www.spigotmc.org/resources/remote-commands.74321/
#

# Version Information:
# Do NOT Change these Values. 
Config-Version: 3.1

# Debug Options:
# Outputs Information about Plugin as it is performing Actions.
# This will flood Console with Messages when active.
# Accepts Boolean Value
# Default is False.
Debug: false

# Server Name:
# Used as Server Identifier when Communicating
# Accepts String Value
Server-Name: Server

# The Pass Key is used to protect against rogue commands being sent to your server.
# All Servers using RemoteCommands must use the same PassKey or Connections will be Denied
# Passkey Must be a Positive Number between 3-6 Digits
# PassKey is sent with a Basic Encryption to Protect your Server
# Accepts Int Value
PassKey: 123456


# The Port-Listener defines what port listeners uses.
# This value must different from any other ports being used on local computer.
# Accepts Int Value 
Port-Listener: 4000

# Server Count:
# Number of Servers to Identify.
# If this value is not correct. the Plugin will not Initialize.
# There is a Maximum of 100 servers you can list. Contact me if you need more
# Accepts Int Value
Server-Count: 4
# To make sure you get the right count, Look at your last server and add 1

##############################
# Command Feature Toggles:
##############################

# Disable Listener:
# Setting this to false will disable all recieve functionality of the plugin.
ListenToggle: true

# Receive Command Toggle:
# This Toggle Controls if the plugin is allowed to recieve Commands from external servers.
RCRToggle: true

# Send Command Toggle: 
# This Toggle Controls if the Plugin can send Commands to External Servers.
RCSToggle: true


# Recieve Broadcast Toggle:
# This Toggle Controls if the plugin is allowed to recieve Broadcasts from external servers.
RBRToggle: true

# Send Broadcast Toggle:
# This Toggle Controls if the plugin can send Broadcasts to External Servers.
RBSToggle: true

