#
# Plugin made by Aikidored
# Discord Support Link: https://discord.gg/RYTfade
#

#
# Remote Commands was made to send commands between multiple seperate 
# servers as long as they are configured correctly.
#

# Version Information:
# Do NOT Change these Values. 
Config-Version: 3.0

# Debug Options:
# Outputs Information about Plugin as it is performing Actions.
# This will flood Console with Messages when active.
# Accepts Boolean Value
# Default is False.
Debug: false

# Server Name:
# Used as Server Identifier when Communicating
# Accepts String Value
Server-Name: Server

# The Pass Key is used to protect against rogue commands being sent to your server.
# All Servers using RemoteCommands must use the same PassKey or Connections will be Denied
# Passkey Must be a Positive Number between 3-6 Digits
# PassKey is sent with a Basic Encryption to Protect your Server
# Accepts Int Value
PassKey: 123456


# The Port-Listener defines what port listeners uses.
# This value must different from any other ports being used on servers computer.
# Accepts Int Value 
Port-Listener: 4000

# Server Count:
# Number of Servers to Identify.
# If this value is not correct. the Plugin will not Initialize.
# There is a Maximum of 100 servers you can list. Contact me if you need more
# Accepts Int Value
Server-Count: 4
# To make sure you get the right count, Look at your last server and add 1
