name: RemoteCommands
main: net.elitegame.aiki.RC.main
version: 3.0
author: aiki
commands:
   RC:
      description: Parent Command for Remote Commands
      usage: /RC [server / Sub-Command] [Message]
      permission: RemoteCommands.use
      permission-message: You don't have remotecommands.use
   RB:
      description: This is a command will Broadcast a Message of your choice to another server
      usage: /RB [server / Command] [Message]
      permission: RemoteBroadcasts.Use
      permission-message: You don't have rb.use. 